export default {
  products: [
    {
      _id: "1",
      name: "running shoes",
      category: "shoes",
      image: "/images/product-1.jpg",
      price: 50,
      branding: "nike",
      rating: 4.5,
      numReviews: 10,
      numInStock: 100,
    },
    {
      _id: "2",
      name: "running shoes",
      category: "shoes",
      image: "/images/product-2.jpg",
      price: 60,
      branding: "nike",
      rating: 4.5,
      numReviews: 10,
      numInStock: 100,
    },
    {
      _id: "3",
      name: "running shoes",
      category: "shoes",
      image: "/images/product-3.jpg",
      price: 70,
      branding: "nike",
      rating: 4.6,
      numReviews: 10,
      numInStock: 10,
    },
    {
      _id: "4",
      name: "running shoes",
      category: "shoes",
      image: "/images/product-4.jpg",
      price: 80,
      branding: "nike",
      rating: 4.6,
      numReviews: 110,
      numInStock: 20,
    },
    {
      _id: "5",
      name: "running shoes",
      category: "shoes",
      image: "/images/product-5.jpg",
      price: 100,
      branding: "nike",
      rating: 4.7,
      numReviews: 100,
      numInStock: 10,
    },
    {
      _id: "6",
      name: "running shoes",
      category: "shoes",
      image: "/images/product-6.jpg",
      price: 130,
      branding: "nike",
      rating: 4.8,
      numReviews: 1000,
      numInStock: 100,
    },
  ],
};
